In [1]:
import numpy as np
import copy

In [2]:
class Queue : # 큐 클래스
    def __init__(self):
        self.items = []
    def enqueue(self, item) :
        self.items.insert(0,item)
    def dequeue(self) :
        return self.items.pop()
    def isEmpty(self) :
        return self.items == []
    def size(self) :
        return len(self.items)

In [3]:
class F : # 현재 이동한 횟수, 현재 있는 점, 현재 상태, 고정하기 위한 상태
    def __init__(self, num, now, data, sdata) :
        self.num = num
        self.now = now
        self.data = data
        self.sdata = sdata

In [4]:
def new(data,now,i) : # 변경된 상태 생성
    data[now][i] = 0
    data[i][now] = 0
    return data

In [5]:
n = int(input()) # 점의 개수 입력

mylist = np.zeros((n,n)) # 행렬 생성

m = int(input()) # 선의 개수

for i in range (m) :
    p, q = map(int, input().split())
    mylist[p][q] += 1
    mylist[q][p] += 1 # 선 입력

4
6
2


ValueError: not enough values to unpack (expected 2, got 1)

In [6]:
sq = Queue() # 큐 생성
sq.enqueue(F(0,0,mylist,mylist)) # 처음 상태 삽입
a = F(0,0,mylist,mylist)
cnt = 0 # 개수

In [7]:
while(sq.size() != 0) : # 큐가 비어있을 때까지
    a = sq.dequeue()
    if(a.now == 2) : # 종점이면 개수 증가
        cnt+=1
    else : # 다른 점과 연결된 선이 있는지 확인
        for i in range(len(a.data[a.now])) :
            a.data = copy.deepcopy(a.sdata)
            if a.data[a.now][i] == 1 : # 있다면 그 점으로 이동 후 큐에 그 상태 삽입
                sq.enqueue(F(a.num+1,i,new(a.data,a.now,i),new(a.data,a.now,i)))

[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]]
[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]]


In [8]:
print(cnt)

1
